version: '3'
services:

  app:
    build: .docker
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/var/www/html
    networks:
      - app-network

  db:
    image: postgres:14
    platform: linux/arm64
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=laravel
      - PGDATA=/var/lib/postgresql/data/db-files/
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
