FROM php:8.1-cli-buster

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libssl-dev \
        libpq-dev \
        libmcrypt-dev \
        libxml2-dev \
        libzip-dev \
        unzip \
        && rm -r /var/lib/apt/lists/*

# Install extention
RUN docker-php-ext-install soap pcntl zip pdo_pgsql bcmath sockets

#####################################
# Composer:
#####################################

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer
# Source the bash
RUN . ~/.bashrc

#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#

####################################
# OPCache:
####################################
RUN docker-php-ext-install opcache

COPY ./php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

ADD ./php/local.ini /usr/local/etc/php/conf.d

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

WORKDIR /var/www

EXPOSE 8080
VOLUME ["/var/www"]
CMD ["bash"]
